version: '3.5'
services:

# Java Service
  java:
    build:
      context: ./
      dockerfile: java.Dockerfile
    container_name: java
    volumes:
      - ./apiserver:/var/www
    restart: unless-stopped
    tty: true
    ports:
      - "8086:8086"
    working_dir: /var/www
    networks:
      - nasanet
    command: ["/bin/bash", "-c", "java -jar build/libs/nasa-rover-challenge-0.0.1-SNAPSHOT.jar"]

  #Nginx Service
  webserver:
    image: nginx:1.18.0
    container_name: webserver
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
    volumes:
      - ./frontend/build:/var/www
      - ./nginx/conf.d:/etc/nginx/conf.d
    networks:
      - nasanet

#Docker Networks
networks:
  nasanet:
    name: nasanet
    driver: bridge
